version: "3.8"

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/watchparty
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=bXlTdXBlclNlY3JldEtleUZvcldhdGNoUGFydHlBcHBsaWNhdGlvbjIwMjY=
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=watchparty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
